/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Kind {
  Keyword = 'Keyword'
}
export const enum Modifier {
  Declaration = 'Declaration'
}
export interface Span {
  start: number
  end: number
  line: number
}
export interface MultiSpan {
  start: Span
  end: Span
}
export interface Highlight {
  span: Span
  kind: Kind
  modifiers: Array<Modifier>
}
export interface Source {
  code: string
  filename: string
}
export function highlights(source: Source): Array<Highlight>
