/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Span {
  start: number
  end: number
  line: number
}
export interface MultiSpan {
  start: Span
  end: Span
}
export interface Highlight {
  span: Span
  kind: string
  modifiers: Array<string>
}
export interface Source {
  code: string
  filename: string
}
export function highlights(source: Source): Array<Highlight>
